name: Publish to PyPi

on:
  push:
    tags:
      - "*"

jobs:
  publish_to_pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.0
          architecture: x64
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Package
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            version=${GITHUB_REF#refs/tags/}
            echo "__version__ = \"$version\"" >> paddock/__version__.py
          fi

          python setup.py sdist bdist_wheel
      - name: Publish to PyPi
        uses: pypa/gh-action-phpi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
